### ISSUE TITLE
Inheritance example

### ISSUE THREAD

**Issue by BotellaA** [master-atul/blog-addons-example#1]
Your ActualClass example is very interesting!

Do you know how to extend your example with inheritance? For instance, by adding another class (let's say SubClass) that inherits from ActualClass?

**Comment by a7ul** [comment]
Hi @BotellaA  Yes, I am currently working on a project that needs to do exactly that. So this is a bit tricky to do, I solved it this way.
The issue is the exported class needs to inherit from a NAPI class only and no other class is allowed there.

So your 
```
class ClassExample : public Napi::ObjectWrap<ClassExample> {
 public:
  static Napi::Object Init(Napi::Env env, Napi::Object exports);
  ClassExample(const Napi::CallbackInfo& info);
  ActualClass* GetInternalInstance();

 private:
  static Napi::FunctionReference constructor;
  Napi::Value GetValue(const Napi::CallbackInfo& info);
  Napi::Value Add(const Napi::CallbackInfo& info);
  ActualClass *actualClass_;
};
```
This has to stay like this only. 
But in your ActualClass

```
class ActualClass: public AnotherClass, public OneMoreClass { //You can inherit all your classes here
 public:
  ActualClass(double value);
  double getValue();
  double add(double toAdd);
 private:
  double value_;
};
```
So The idea is to preapare a subclass that can be exported.

**Comment by a7ul** [comment]
Maybe I can help you more if you can post  a snippet.

**Comment by BotellaA** [comment]
Let's continue your example.
```
class AnotherClass { 
 public:
  AnotherClass (int value);
  int getAnotherValue();
 private:
  int value_;
};
class ActualClass: public AnotherClass {
 public:
  ActualClass(double value, int another_value): AnotherClass( another_value ), value_( value ) {}
  double getValue();
  double add(double toAdd);
 private:
  double value_;
};
```
Its own wrapper:
```
class AnotherClassExample : public Napi::ObjectWrap<AnotherClassExample > {
 public:
  static Napi::Object Init(Napi::Env env, Napi::Object exports);
  AnotherClassExample (const Napi::CallbackInfo& info);
  AnotherClass* GetInternalInstance();

 private:
  static Napi::FunctionReference constructor;
  Napi::Value GetAnotherValue(const Napi::CallbackInfo& info);
  AnotherClass* anotherClass_;
};
```
And I would like to run something like that:
```
const testAddon = require('./build/Release/testaddon.node');
const another = new testAddon.AnotherClassExample(1);
console.log('Another value : ', another .getAnotherValue());

const actual = new testAddon.ClassExample(4.3, 1);
console.log('Actual value : ', actual .getValue());
console.log('Another value : ', actual .getAnotherValue());
```

What should I write inside the ```ClassExample::Init``` to do this?

**Comment by a7ul** [comment]
Perfect!
So ClassExampple Init would look something like this
```
Napi::Object ClassExample::Init(Napi::Env env, Napi::Object exports) {
  Napi::HandleScope scope(env);

  Napi::Function func = DefineClass(env, "ClassExample", {
    InstanceMethod("add", &ClassExample::Add),
    InstanceMethod("getValue", &ClassExample::GetValue),
  });

  constructor = Napi::Persistent(func);
  constructor.SuppressDestruct();

  exports.Set("ClassExample", func);
  return exports;
}
```
and AnotherClass Init would look something like this:
```
Napi::Object AnotherClassExample::Init(Napi::Env env, Napi::Object exports) {
  Napi::HandleScope scope(env);

  Napi::Function func = DefineClass(env, "AnotherClassExample", {
    InstanceMethod("getAnotherValue", &AnotherClassExample::GetAnotherValue),
    InstanceMethod("getValue", &AnotherClassExample::GetValue),
  });

  constructor = Napi::Persistent(func);
  constructor.SuppressDestruct();

  exports.Set("AnotherClassExample", func);
  return exports;
}
```

Notice that during `exports.Set` we are using two different keys. So it will set both ClassExample and AnotherClassExample keys on the exports object.

Now In your main.cpp
```
#include <napi.h>
#include "Samples/anotherclassexample.h"
#include "Samples/classexample.h"

Napi::Object InitAll(Napi::Env env, Napi::Object exports) {
  AnotherClassExample::Init(env, exports); //here the AnotherClass key will be set
  return ClassExample::Init(env, exports); //here the ClassExample key will be set
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, InitAll)
```

So you will get both the classes exported in two different keys.
Hope this answers your question.

**Comment by BotellaA** [comment]
Thanks for your example. 

So to sum up with another example to make sure I understood well: if I have 3 classes (A, B and C) and C inherits from B, B inherits from A. Let's assume each class has 10 methods to exports. Then the ObjectWrap of A exports 10 methods, B exports 20 methods and C 30 methods. 

This will works but seems redundant. Is there any way to avoid explicitly export A's methods both in the B and C ObjectWrap?

**Comment by a7ul** [comment]
Yes, I am also currently facing the same situation in one of my projects. I wasn't able to figure out another way to export them. I had to manually export each and every method :( .  
Do let me know if you find another way. It would be of great help to me aswell .

**Comment by BotellaA** [comment]
Ok, I will comment on this thread if I find something. Hopefully you will do the same 😉
